[package]
name = "bigint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rust_fib"
crate-type = ["cdylib"]

[dependencies]
num-bigint = "0.4.4"
num-traits = "0.2.17"
pyo3 = "0.20"

