[package]
name = "axumapp02"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.7.2"
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.5.0", features = ["fs", "trace"] }
